In [119]:
import numpy as np
import pandas as pd
import sympy as sy
from numpy.random import randn 

In [120]:
array_1 = np.array([1,2,3,4])

In [121]:
array_2 = np.array([4,3,2,1])

In [122]:
len(array_1)+1

5

In [123]:
# for i in range(len(array_1)):
#     dot = sum(array_1[i]*array_2)
#     dot
#     #Do not use this

In [124]:
dot = 0
for e,f in zip(array_1,array_2):
    dot += e*f
dot

20

In [125]:
dot

20

In [126]:
array_1@array_2

20

In [127]:
array_1.dot(array_2)

20

In [128]:
array_3 = np.sqrt(array_1)

In [129]:
array_3

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [130]:
another_arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [131]:
another_arr[0:5]

array([1, 2, 3, 4, 5])

# Broadcasting

In [132]:
another_arr[0:5]=100

In [133]:
another_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [134]:
another_arr[:] = 1

In [135]:
another_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [136]:
three_by_three = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [137]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
#three_by_three[:]  = 0
a_list = [1,2,3,4,5]

In [139]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
# I want to grab the first column in three_by_three

In [141]:
three_by_three[:,1]

array([2, 5, 8])

In [142]:
#Slicing _ HW due this Monday.

In [143]:
three_by_three > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [144]:
new_matrix = three_by_three > 4

In [145]:
new_matrix

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [146]:
M = sy.Matrix([[1,2,3],[4,5,6],[7,8,9]])
M

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [147]:
N = M.inv()
N

NonInvertibleMatrixError: Matrix det == 0; not invertible.

In [148]:
P = sy.Matrix([[1,2,3],[4,1,2],[7,8,9]])
P

Matrix([
[1, 2, 3],
[4, 1, 2],
[7, 8, 9]])

In [150]:
Q = P.inv()
Q

Matrix([
[ -7/24,  1/4,  1/24],
[-11/12, -1/2,  5/12],
[ 25/24,  1/4, -7/24]])

In [151]:
Q@P

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [154]:
np.dot(Q,P)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=object)

In [156]:
np.matmul(P,Q)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=object)

In [100]:
T = sy.Matrix(np.random.randint(-7,5, size=(2,2)))
T

Matrix([
[-7, -5],
[ 1,  0]])

In [101]:
I = sy.eye(3,5)
I

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0]])

In [102]:
Z = sy.zeros(3,3)
Z

Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

In [103]:
O = sy.ones(4,4)
O

Matrix([
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1]])

In [104]:
D = sy.diag(1,2,3)
D

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [109]:
L = np.linspace(1,25,25)

In [112]:
len(L)

25

In [113]:
M = L.reshape(5,5)
M

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [164]:
eig_val, eig_vec = M.np.linalg.eigh

AttributeError: 'MutableDenseMatrix' object has no attribute 'np'

In [157]:
list_a = [1,2,3,4,5]
label = ['a','b','c','d','e']
a_dict = {'a':1,'b':2,'c':3,'d':4,'e':5}

In [159]:
first_df = pd.Series(data=list_a)
first_df.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [160]:
second_df = pd.Series(data=list_a, index=label)
second_df.head()

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [161]:
third_df = pd.Series(list_a,label)
third_df.head()

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [163]:
dict_df = pd.Series(a_dict)
dict_df.head()

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
from numpy.random import randn

In [15]:
data= np.random.randint(20,100, size=10)

In [16]:
df = pd.DataFrame(data, columns=['A'])
df.head()

A
0  51
1  26
2  85
3  24
4  87

In [17]:
# Adding one more column
data1 = np.random.randint(10,70, size=10)

In [18]:
df['B'] = data1
df.head()

A   B
0  51  19
1  26  30
2  85  50
3  24  44
4  87  38

In [19]:
# Adding a third column
data2 = np.random.randint(110,170, size=10)
df['C']= data2

In [20]:
df.head(7)

A   B    C
0  51  19  169
1  26  30  158
2  85  50  130
3  24  44  137
4  87  38  114
5  70  41  162
6  49  65  157

In [21]:
df[((df['A']+df['B'] > df['C']) & (df['B']+df['C'] > df['A']))]

A   B    C
2  85  50  130
4  87  38  114
8  98  48  143

In [22]:
df[((df['A']+df['B'] > df['C']) | (df['B']+df['C'] > df['A'])) | ((df['A']+df['C'] > df['B']))].count()

A    10
B    10
C    10
dtype: int64

In [57]:
df = pd.DataFrame(randn(6,5),index='A B C D E F'.split(), columns='V/W/X/Y/Z'.split('/'))
df

V         W         X         Y         Z
A  0.181538  2.270561  0.143684 -0.147032 -0.461588
B -2.537607 -1.320967  1.419160 -0.960333  1.164217
C  1.486992 -1.375576  0.011131  0.080940  0.700034
D  0.370324  1.661131  1.496199  0.535266 -1.245266
E -0.228571  1.861546  0.007024 -1.113793 -1.445440
F  0.201480  0.362908  0.609422 -1.614015 -1.235753

In [58]:
df > 0

V      W     X      Y      Z
A   True   True  True  False  False
B  False  False  True  False   True
C   True  False  True   True   True
D   True   True  True   True  False
E  False   True  True  False  False
F   True   True  True  False  False

In [59]:
df[df > 0]

V         W         X         Y         Z
A  0.181538  2.270561  0.143684       NaN       NaN
B       NaN       NaN  1.419160       NaN  1.164217
C  1.486992       NaN  0.011131  0.080940  0.700034
D  0.370324  1.661131  1.496199  0.535266       NaN
E       NaN  1.861546  0.007024       NaN       NaN
F  0.201480  0.362908  0.609422       NaN       NaN

In [60]:
df[df>0][['Y','Z']]

Y         Z
A       NaN       NaN
B       NaN  1.164217
C  0.080940  0.700034
D  0.535266       NaN
E       NaN       NaN
F       NaN       NaN

In [61]:
df[(df['W']>0) & (df['Y']>0)]

V         W         X         Y         Z
D  0.370324  1.661131  1.496199  0.535266 -1.245266

In [62]:
df[(df['W']>0) & (df['Y']<1)][['W','Y']]

W         Y
A  2.270561 -0.147032
D  1.661131  0.535266
E  1.861546 -1.113793
F  0.362908 -1.614015

In [63]:
df.loc['E']['V'] 

-0.2285708865745408

In [64]:
df.loc[['A','B']]

V         W         X         Y         Z
A  0.181538  2.270561  0.143684 -0.147032 -0.461588
B -2.537607 -1.320967  1.419160 -0.960333  1.164217

In [65]:
df.loc[['A','B'],['X','Y']]

X         Y
A  0.143684 -0.147032
B  1.419160 -0.960333

In [66]:
df.columns

Index(['V', 'W', 'X', 'Y', 'Z'], dtype='object')

In [67]:
new_columns_name=['col1','col2','col3','col4','col5']

In [68]:
df.columns = new_columns_name

In [69]:
df.head()

col1      col2      col3      col4      col5
A  0.181538  2.270561  0.143684 -0.147032 -0.461588
B -2.537607 -1.320967  1.419160 -0.960333  1.164217
C  1.486992 -1.375576  0.011131  0.080940  0.700034
D  0.370324  1.661131  1.496199  0.535266 -1.245266
E -0.228571  1.861546  0.007024 -1.113793 -1.445440

In [90]:
na_df = df[df > -1.5]
na_df.head()

col1      col2      col3      col4      col5
A  0.181538  2.270561  0.143684 -0.147032 -0.461588
B       NaN -1.320967  1.419160 -0.960333  1.164217
C  1.486992 -1.375576  0.011131  0.080940  0.700034
D  0.370324  1.661131  1.496199  0.535266 -1.245266
E -0.228571  1.861546  0.007024 -1.113793 -1.445440

In [91]:
na_df.isna().sum()

col1    1
col2    0
col3    0
col4    1
col5    0
dtype: int64

In [92]:
na_df.dropna(axis=1)

col2      col3      col5
A  2.270561  0.143684 -0.461588
B -1.320967  1.419160  1.164217
C -1.375576  0.011131  0.700034
D  1.661131  1.496199 -1.245266
E  1.861546  0.007024 -1.445440
F  0.362908  0.609422 -1.235753

In [93]:
na_df.head()

col1      col2      col3      col4      col5
A  0.181538  2.270561  0.143684 -0.147032 -0.461588
B       NaN -1.320967  1.419160 -0.960333  1.164217
C  1.486992 -1.375576  0.011131  0.080940  0.700034
D  0.370324  1.661131  1.496199  0.535266 -1.245266
E -0.228571  1.861546  0.007024 -1.113793 -1.445440

In [96]:
na_df.fillna(value = 2022, axis=1)

col1      col2      col3         col4      col5
A     0.181538  2.270561  0.143684    -0.147032 -0.461588
B  2022.000000 -1.320967  1.419160    -0.960333  1.164217
C     1.486992 -1.375576  0.011131     0.080940  0.700034
D     0.370324  1.661131  1.496199     0.535266 -1.245266
E    -0.228571  1.861546  0.007024    -1.113793 -1.445440
F     0.201480  0.362908  0.609422  2022.000000 -1.235753

In [98]:
df1 = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [13]:
df1

W         X         Y         Z
A -1.248783  0.138449  0.422566  0.032521
B  0.577158  0.265700  0.539462 -1.038276
C -0.057982 -0.215341  0.500690 -0.228471
D -1.091893 -1.265938  0.349193  0.505694
E -0.354188  0.861065  0.472820 -0.606225

In [52]:
df = pd.DataFrame(np.random.rand(5,4),index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [58]:
df

W         X         Y         Z
A -0.624831 -1.929624 -0.446598 -0.919975
B -0.410590 -0.925560  0.485867  0.963867
C -1.065603  1.171810 -0.894292  0.968977
D -0.257317  0.284101 -0.508430  0.411544
E -0.945525  1.013095  1.481431 -0.640545

In [59]:
df['W']

A   -0.624831
B   -0.410590
C   -1.065603
D   -0.257317
E   -0.945525
Name: W, dtype: float64

In [60]:
# I want to grab the first two columns
df[['W', 'X']]

W         X
A -0.624831 -1.929624
B -0.410590 -0.925560
C -1.065603  1.171810
D -0.257317  0.284101
E -0.945525  1.013095

In [61]:
type(df.W)

pandas.core.series.Series

In [41]:
df['New'] = df['W']+df['Y']

In [42]:
df

W         X         Y         Z       New
A  1.540633 -0.445608 -0.127311 -0.521802  1.413322
B  0.617799  0.518330  1.089684 -2.226846  1.707483
C  0.023449 -0.527552 -0.841624  0.411606 -0.818175
D  0.067791  0.478769 -0.352596 -0.289912 -0.284805
E -0.188098  0.460871 -0.392400 -2.136431 -0.580498

In [43]:
df.drop('New', axis=1)

W         X         Y         Z
A  1.540633 -0.445608 -0.127311 -0.521802
B  0.617799  0.518330  1.089684 -2.226846
C  0.023449 -0.527552 -0.841624  0.411606
D  0.067791  0.478769 -0.352596 -0.289912
E -0.188098  0.460871 -0.392400 -2.136431

In [44]:
df.drop('New', axis=1, inplace=True)

In [45]:
df

W         X         Y         Z
A  1.540633 -0.445608 -0.127311 -0.521802
B  0.617799  0.518330  1.089684 -2.226846
C  0.023449 -0.527552 -0.841624  0.411606
D  0.067791  0.478769 -0.352596 -0.289912
E -0.188098  0.460871 -0.392400 -2.136431